sudo: required
services:
 - docker
 
before_install:
 - docker build -t laurentiuleitan/docker-react -f Dockerfile.dev .

script:
 - docker run laurentiuleitan/docker-react npm run test -- --coverage
