FROM node:alpine

# Set proxy - must be done when running from the Conti nw
ENV http_proxy "http://uidt589z:Windows2000@cias3basic.conti.de:8080"
ENV https_proxy "http://uidt589z:Windows2000@cias3basic.conti.de:8080"

WORKDIR '/app'

COPY ./package.json ./
RUN npm install

COPY . .

CMD ["npm", "run", "start"]

